// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyShop.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyShop.Data.Migrations
{
    [DbContext(typeof(MyShopDbContext))]
    [Migration("20251229161830_AddProductImagesAndSeedData")]
    partial class AddProductImagesAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyShop.Data.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Electronic devices and gadgets for everyday use",
                            Name = "Electronics"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Fashion clothing and apparel for men, women, and children",
                            Name = "Clothing"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Home furniture, decor, and garden supplies",
                            Name = "Home & Garden"
                        });
                });

            modelBuilder.Entity("MyShop.Data.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("FinalPrice")
                        .HasColumnType("integer");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MyShop.Data.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("integer");

                    b.Property<float>("UnitSalePrice")
                        .HasColumnType("real");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MyShop.Data.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageUrl1")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImageUrl2")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImageUrl3")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ImportPrice")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Count = 100,
                            Description = "High-quality Wireless Headphones for professional and personal use",
                            ImageUrl1 = "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1612465289702-7c84b5258fde?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8V2lyZWxlc3MlMjBIZWFkcGhvbmVzfGVufDB8fDB8fHww",
                            ImageUrl3 = "https://images.unsplash.com/photo-1619296794093-3df1ae6819a8?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fFdpcmVsZXNzJTIwSGVhZHBob25lc3xlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 50000,
                            Name = "Wireless Headphones",
                            Sku = "ELEC-001"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Count = 98,
                            Description = "High-quality USB-C Cable for professional and personal use",
                            ImageUrl1 = "https://images.unsplash.com/photo-1711056831898-97718f6972d3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8VVNCLUMlMjBDYWJsZXxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1615086169217-83e1c06c9f4f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fFVTQi1DJTIwQ2FibGV8ZW58MHx8MHx8fDA%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1762681290814-432626dffb8c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8VVNCLUMlMjBDYWJsZXxlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 65000,
                            Name = "USB-C Cable",
                            Sku = "ELEC-002"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Count = 96,
                            Description = "High-quality Phone Stand for professional and personal use",
                            ImageUrl1 = "https://images.unsplash.com/photo-1617975426095-f073792aef15?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8UGhvbmUlMjBTdGFuZHxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1553556135-009e5858adce?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8UGhvbmUlMjBTdGFuZHxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1707651385176-8c7492596164?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8UGhvbmUlMjBTdGFuZHxlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 80000,
                            Name = "Phone Stand",
                            Sku = "ELEC-003"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            Count = 94,
                            Description = "High-quality Portable Charger for professional and personal use",
                            ImageUrl1 = "https://images.unsplash.com/photo-1706275399494-fb26bbc5da63?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8UG9ydGFibGUlMjBDaGFyZ2VyfGVufDB8fDB8fHww",
                            ImageUrl2 = "https://images.unsplash.com/photo-1736516434209-51ece1006788?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8UG9ydGFibGUlMjBDaGFyZ2VyfGVufDB8fDB8fHww",
                            ImageUrl3 = "https://images.unsplash.com/photo-1745888323448-36957ea892f5?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fFBvcnRhYmxlJTIwQ2hhcmdlcnxlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 95000,
                            Name = "Portable Charger",
                            Sku = "ELEC-004"
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1,
                            Count = 92,
                            Description = "High-quality Screen Protector for professional and personal use",
                            ImageUrl1 = "https://images.unsplash.com/photo-1714058948949-4414c2007759?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8U2NyZWVuJTIwUHJvdGVjdG9yfGVufDB8fDB8fHww",
                            ImageUrl2 = "https://images.unsplash.com/photo-1636614597280-3dde89cbd6cc?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8U2NyZWVuJTIwUHJvdGVjdG9yfGVufDB8fDB8fHwwhttps://images.unsplash.com/photo-1636614597280-3dde89cbd6cc?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8U2NyZWVuJTIwUHJvdGVjdG9yfGVufDB8fDB8fHww",
                            ImageUrl3 = "https://images.unsplash.com/photo-1567428486597-8c5328fd3816?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8U2NyZWVuJTIwUHJvdGVjdG9yfGVufDB8fDB8fHww",
                            ImportPrice = 110000,
                            Name = "Screen Protector",
                            Sku = "ELEC-005"
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 1,
                            Count = 90,
                            Description = "High-quality Phone Case for professional and personal use",
                            ImageUrl1 = "https://images.unsplash.com/photo-1535157412991-2ef801c1748b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8UGhvbmUlMjBDYXNlfGVufDB8fDB8fHww",
                            ImageUrl2 = "https://images.unsplash.com/photo-1593055454503-531d165c2ed8?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8UGhvbmUlMjBDYXNlfGVufDB8fDB8fHww",
                            ImageUrl3 = "https://images.unsplash.com/photo-1623393884989-cb3663e431c5?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8UGhvbmUlMjBDYXNlfGVufDB8fDB8fHww",
                            ImportPrice = 125000,
                            Name = "Phone Case",
                            Sku = "ELEC-006"
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1,
                            Count = 88,
                            Description = "High-quality Bluetooth Speaker for professional and personal use",
                            ImageUrl1 = "https://images.unsplash.com/photo-1589256469067-ea99122bbdc4?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Ymx1ZXRvb3RoJTIwc3BlYWtlcnxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1589003077984-894e133dabab?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Ymx1ZXRvb3RoJTIwc3BlYWtlcnxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1588131153911-a4ea5189fe19?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGJsdWV0b290aCUyMHNwZWFrZXJ8ZW58MHx8MHx8fDA%3D",
                            ImportPrice = 140000,
                            Name = "Bluetooth Speaker",
                            Sku = "ELEC-007"
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 1,
                            Count = 86,
                            Description = "High-quality USB Hub for professional and personal use",
                            ImageUrl1 = "https://images.unsplash.com/photo-1760376789487-994070337c76?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8VVNCJTIwSHVifGVufDB8fDB8fHww",
                            ImageUrl2 = "https://images.unsplash.com/photo-1760376789478-c1023d2dc007?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8VVNCJTIwSHVifGVufDB8fDB8fHww",
                            ImageUrl3 = "https://images.unsplash.com/photo-1616578273461-3a99ce422de6?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8VVNCJTIwSHVifGVufDB8fDB8fHww",
                            ImportPrice = 155000,
                            Name = "USB Hub",
                            Sku = "ELEC-008"
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 1,
                            Count = 84,
                            Description = "High-quality HDMI Cable for professional and personal use",
                            ImageUrl1 = "https://images.unsplash.com/photo-1756043827134-dcc8ac7462f6?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8SERNSSUyMENhYmxlfGVufDB8fDB8fHww",
                            ImageUrl2 = "https://images.unsplash.com/photo-1760377821967-8bb2f250e041?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8SERNSSUyMENhYmxlfGVufDB8fDB8fHww",
                            ImageUrl3 = "https://images.unsplash.com/photo-1649959223405-f927e0fc1e05?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fEhETUklMjBDYWJsZXxlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 170000,
                            Name = "HDMI Cable",
                            Sku = "ELEC-009"
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 1,
                            Count = 82,
                            Description = "High-quality Memory Card 64GB for professional and personal use",
                            ImageUrl1 = "https://images.unsplash.com/photo-1632251350035-7f750a5973b6?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8TWVtb3J5JTIwQ2FyZCUyMDY0R0J8ZW58MHx8MHx8fDA%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1739742473106-6d9bb5409d4a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8TWVtb3J5JTIwQ2FyZCUyMDY0R0J8ZW58MHx8MHx8fDA%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1541095740744-65daee21c422?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fE1lbW9yeSUyMENhcmQlMjA2NEdCfGVufDB8fDB8fHww",
                            ImportPrice = 185000,
                            Name = "Memory Card 64GB",
                            Sku = "ELEC-010"
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 1,
                            Count = 80,
                            Description = "High-quality Webcam for professional and personal use",
                            ImageUrl1 = "https://images.unsplash.com/photo-1623949556303-b0d17d198863?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8d2ViY2FtfGVufDB8fDB8fHww",
                            ImageUrl2 = "https://images.unsplash.com/photo-1626581795188-8efb9a00eeec?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHdlYmNhbXxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1629429407756-446d66f5b24e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHdlYmNhbXxlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 200000,
                            Name = "Webcam",
                            Sku = "ELEC-011"
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 1,
                            Count = 78,
                            Description = "High-quality USB Keyboard for professional and personal use",
                            ImageUrl1 = "https://images.unsplash.com/photo-1743862558324-64de6d680fbb?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NTZ8fFVTQiUyMEtleWJvYXJkfGVufDB8fDB8fHww",
                            ImageUrl2 = "https://images.unsplash.com/photo-1584727151652-d09b17ebf23f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Njd8fFVTQiUyMEtleWJvYXJkfGVufDB8fDB8fHww",
                            ImageUrl3 = "https://images.unsplash.com/photo-1629087667662-632024eabb1e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NzV8fFVTQiUyMEtleWJvYXJkfGVufDB8fDB8fHww",
                            ImportPrice = 215000,
                            Name = "USB Keyboard",
                            Sku = "ELEC-012"
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 1,
                            Count = 76,
                            Description = "High-quality Wireless Mouse for professional and personal use",
                            ImageUrl1 = "https://images.unsplash.com/photo-1660491083562-d91a64d6ea9c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8V2lyZWxlc3MlMjBNb3VzZXxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl2 = "http://images.unsplash.com/photo-1707592691247-5c3a1c7ba0e3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8V2lyZWxlc3MlMjBNb3VzZXxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1527814050087-3793815479db?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8V2lyZWxlc3MlMjBNb3VzZXxlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 230000,
                            Name = "Wireless Mouse",
                            Sku = "ELEC-013"
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 1,
                            Count = 74,
                            Description = "High-quality Laptop Stand for professional and personal use",
                            ImageUrl1 = "https://images.unsplash.com/photo-1623251606108-512c7c4a3507?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8TGFwdG9wJTIwU3RhbmR8ZW58MHx8MHx8fDA%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1629317480826-910f729d1709?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8TGFwdG9wJTIwU3RhbmR8ZW58MHx8MHx8fDA%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1575399545768-5f1840c1312d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8TGFwdG9wJTIwU3RhbmR8ZW58MHx8MHx8fDA%3D",
                            ImportPrice = 245000,
                            Name = "Laptop Stand",
                            Sku = "ELEC-014"
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 1,
                            Count = 72,
                            Description = "High-quality Monitor Stand for professional and personal use",
                            ImageUrl1 = "https://images.unsplash.com/photo-1760278042013-e6a4866c4c81?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDZ8fE1vbml0b3IlMjBTdGFuZHxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1765805913682-03457777186a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDd8fE1vbml0b3IlMjBTdGFuZHxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1643131747793-1b103cc66c6b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDh8fE1vbml0b3IlMjBTdGFuZHxlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 260000,
                            Name = "Monitor Stand",
                            Sku = "ELEC-015"
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 1,
                            Count = 70,
                            Description = "High-quality Cable Organizer for professional and personal use",
                            ImageUrl1 = "https://images.unsplash.com/photo-1760348213270-7cd00b8c3405?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Q2FibGUlMjBPcmdhbml6ZXJ8ZW58MHx8MHx8fDA%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1746123725998-c0f6dcdda373?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjJ8fENhYmxlJTIwT3JnYW5pemVyfGVufDB8fDB8fHww",
                            ImageUrl3 = "https://images.unsplash.com/photo-1635335874521-7987db781153?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NTZ8fENhYmxlJTIwT3JnYW5pemVyfGVufDB8fDB8fHww",
                            ImportPrice = 275000,
                            Name = "Cable Organizer",
                            Sku = "ELEC-016"
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 1,
                            Count = 68,
                            Description = "High-quality Phone Screen Cleaner for professional and personal use",
                            ImageUrl1 = "https://images.unsplash.com/photo-1623691136531-68d65f1a25a0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NTV8fFBob25lJTIwU2NyZWVuJTIwQ2xlYW5lcnxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1657180949872-349249fd1f63?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjQ4fHxQaG9uZSUyMFNjcmVlbiUyMENsZWFuZXJ8ZW58MHx8MHx8fDA%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1603285991346-3f4eb15808d4?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjZ8fHBob25lJTIwc2NyZWVuJTIwY2xlYW5lcnxlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 290000,
                            Name = "Phone Screen Cleaner",
                            Sku = "ELEC-017"
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 1,
                            Count = 66,
                            Description = "High-quality Charging Dock for professional and personal use",
                            ImageUrl1 = "https://images.unsplash.com/photo-1761311985502-8d132eb2ba73?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fENoYXJnaW5nJTIwRG9ja3xlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1760462788374-fe0d2d4ba4d1?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fENoYXJnaW5nJTIwRG9ja3xlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1760462788238-c9111e060692?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjJ8fENoYXJnaW5nJTIwRG9ja3xlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 305000,
                            Name = "Charging Dock",
                            Sku = "ELEC-018"
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 1,
                            Count = 64,
                            Description = "High-quality Power Bank 20000mAh for professional and personal use",
                            ImageUrl1 = "https://images.unsplash.com/photo-1706275399512-81a6c7267234?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjR8fHBvd2VyJTIwYmF0dGVyeSUyMDIwMDAwbUFofGVufDB8fDB8fHww",
                            ImageUrl2 = "https://images.unsplash.com/photo-1706275399494-fb26bbc5da63?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDJ8fHBvd2VyJTIwYmF0dGVyeSUyMDIwMDAwbUFofGVufDB8fDB8fHww",
                            ImageUrl3 = "https://images.unsplash.com/photo-1581104678061-1a4fe238863e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NzB8fHBvd2VyJTIwYmF0dGVyeSUyMDIwMDAwbUFofGVufDB8fDB8fHww",
                            ImportPrice = 320000,
                            Name = "Power Bank 20000mAh",
                            Sku = "ELEC-019"
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 1,
                            Count = 62,
                            Description = "High-quality Type-C Adapter for professional and personal use",
                            ImageUrl1 = "https://images.unsplash.com/photo-1594549181132-9045fed330ce?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8VHlwZS1DJTIwQWRhcHRlcnxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1594549181132-9045fed330ce?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8VHlwZS1DJTIwQWRhcHRlcnxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1594549181132-9045fed330ce?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8VHlwZS1DJTIwQWRhcHRlcnxlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 335000,
                            Name = "Type-C Adapter",
                            Sku = "ELEC-020"
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 1,
                            Count = 60,
                            Description = "High-quality Lightning Cable for professional and personal use",
                            ImageUrl1 = "https://images.unsplash.com/photo-1738520420654-87cd2ad005d0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8TGlnaHRuaW5nJTIwQ2FibGV8ZW58MHx8MHx8fDA%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1595392029711-8a206145f976?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8TGlnaHRuaW5nJTIwQ2FibGV8ZW58MHx8MHx8fDA%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1607087365600-e7bf50d0b226?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8TGlnaHRuaW5nJTIwQ2FibGV8ZW58MHx8MHx8fDA%3D",
                            ImportPrice = 350000,
                            Name = "Lightning Cable",
                            Sku = "ELEC-021"
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 1,
                            Count = 58,
                            Description = "High-quality Network Switch for professional and personal use",
                            ImageUrl1 = "https://images.unsplash.com/photo-1520869562399-e772f042f422?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8TmV0d29yayUyMFN3aXRjaHxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1531765408077-9a1f85f90df1?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8TmV0d29yayUyMFN3aXRjaHxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1682559736721-c2e77ff4c650?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8TmV0d29yayUyMFN3aXRjaHxlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 365000,
                            Name = "Network Switch",
                            Sku = "ELEC-022"
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryId = 2,
                            Count = 200,
                            Description = "Premium quality Cotton T-Shirt made from comfortable and durable materials",
                            ImageUrl1 = "https://images.unsplash.com/photo-1651761179569-4ba2aa054997?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y290dG9uJTIwdCUyMHNoaXJ0fGVufDB8fDB8fHww",
                            ImageUrl2 = "https://images.unsplash.com/photo-1759572095384-1a7e646d0d4f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Y290dG9uJTIwdCUyMHNoaXJ0fGVufDB8fDB8fHww",
                            ImageUrl3 = "https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGNvdHRvbiUyMHQlMjBzaGlydHxlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 100000,
                            Name = "Cotton T-Shirt",
                            Sku = "CLTH-001"
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryId = 2,
                            Count = 197,
                            Description = "Premium quality Jeans made from comfortable and durable materials",
                            ImageUrl1 = "https://images.unsplash.com/photo-1602293589930-45aad59ba3ab?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8SmVhbnN8ZW58MHx8MHx8fDA%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1542272604-787c3835535d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8SmVhbnN8ZW58MHx8MHx8fDA%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1598554747436-c9293d6a588f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8SmVhbnN8ZW58MHx8MHx8fDA%3D",
                            ImportPrice = 112000,
                            Name = "Jeans",
                            Sku = "CLTH-002"
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = 2,
                            Count = 194,
                            Description = "Premium quality Polo Shirt made from comfortable and durable materials",
                            ImageUrl1 = "https://images.unsplash.com/photo-1625910513413-c23b8bb81cba?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8UG9sbyUyMFNoaXJ0fGVufDB8fDB8fHww",
                            ImageUrl2 = "https://images.unsplash.com/photo-1625910513520-bed0389ce32f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8UG9sbyUyMFNoaXJ0fGVufDB8fDB8fHww",
                            ImageUrl3 = "https://images.unsplash.com/photo-1625910513399-c9fcba54338c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8UG9sbyUyMFNoaXJ0fGVufDB8fDB8fHww",
                            ImportPrice = 124000,
                            Name = "Polo Shirt",
                            Sku = "CLTH-003"
                        },
                        new
                        {
                            ProductId = 26,
                            CategoryId = 2,
                            Count = 191,
                            Description = "Premium quality Casual Shorts made from comfortable and durable materials",
                            ImageUrl1 = "https://images.unsplash.com/photo-1765438867937-90c60e6ce2ec?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzB8fENhc3VhbCUyMFNob3J0c3xlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1758541331115-29587869e93f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDd8fENhc3VhbCUyMFNob3J0c3xlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1766215565880-d57e8c94538a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NjB8fENhc3VhbCUyMFNob3J0c3xlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 136000,
                            Name = "Casual Shorts",
                            Sku = "CLTH-004"
                        },
                        new
                        {
                            ProductId = 27,
                            CategoryId = 2,
                            Count = 188,
                            Description = "Premium quality Sweater made from comfortable and durable materials",
                            ImageUrl1 = "https://images.unsplash.com/photo-1574201635302-388dd92a4c3f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8c3dlYXRlcnxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1631541909061-71e349d1f203?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8c3dlYXRlcnxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl3 = "https://plus.unsplash.com/premium_photo-1695339146296-ab03c0e6ae50?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8c3dlYXRlcnxlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 148000,
                            Name = "Sweater",
                            Sku = "CLTH-005"
                        },
                        new
                        {
                            ProductId = 28,
                            CategoryId = 2,
                            Count = 185,
                            Description = "Premium quality Hoodie made from comfortable and durable materials",
                            ImageUrl1 = "https://images.unsplash.com/photo-1620799140188-3b2a02fd9a77?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8SG9vZGllfGVufDB8fDB8fHww",
                            ImageUrl2 = "https://images.unsplash.com/photo-1564557287817-3785e38ec1f5?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8SG9vZGllfGVufDB8fDB8fHww",
                            ImageUrl3 = "https://images.unsplash.com/photo-1601063476271-a159c71ab0b3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fEhvb2RpZXxlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 160000,
                            Name = "Hoodie",
                            Sku = "CLTH-006"
                        },
                        new
                        {
                            ProductId = 29,
                            CategoryId = 2,
                            Count = 182,
                            Description = "Premium quality Jacket made from comfortable and durable materials",
                            ImageUrl1 = "https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8SmFja2V0fGVufDB8fDB8fHww",
                            ImageUrl2 = "https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fEphY2tldHxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1557418669-db3f781a58c0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fEphY2tldHxlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 172000,
                            Name = "Jacket",
                            Sku = "CLTH-007"
                        },
                        new
                        {
                            ProductId = 30,
                            CategoryId = 2,
                            Count = 179,
                            Description = "Premium quality Chinos Pants made from comfortable and durable materials",
                            ImageUrl1 = "https://images.unsplash.com/photo-1584865288642-42078afe6942?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Q2hpbm9zJTIwUGFudHN8ZW58MHx8MHx8fDA%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1764816657611-8b1bd2d72cce?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Q2hpbm9zJTIwUGFudHN8ZW58MHx8MHx8fDA%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1610892923471-d8efa48225d0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjZ8fENoaW5vcyUyMFBhbnRzfGVufDB8fDB8fHww",
                            ImportPrice = 184000,
                            Name = "Chinos Pants",
                            Sku = "CLTH-008"
                        },
                        new
                        {
                            ProductId = 31,
                            CategoryId = 2,
                            Count = 176,
                            Description = "Premium quality Dress Shirt made from comfortable and durable materials",
                            ImageUrl1 = "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8RHJlc3MlMjBTaGlydHxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1603252109612-24fa03d145c8?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8RHJlc3MlMjBTaGlydHxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1603252109303-2751441dd157?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8RHJlc3MlMjBTaGlydHxlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 196000,
                            Name = "Dress Shirt",
                            Sku = "CLTH-009"
                        },
                        new
                        {
                            ProductId = 32,
                            CategoryId = 2,
                            Count = 173,
                            Description = "Premium quality Baseball Cap made from comfortable and durable materials",
                            ImageUrl1 = "https://images.unsplash.com/photo-1720534490358-bc2ad29d51d5?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8QmFzZWJhbGwlMjBDYXB8ZW58MHx8MHx8fDA%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1691256676359-20e5c6d4bc92?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8QmFzZWJhbGwlMjBDYXB8ZW58MHx8MHx8fDA%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8QmFzZWJhbGwlMjBDYXB8ZW58MHx8MHx8fDA%3D",
                            ImportPrice = 208000,
                            Name = "Baseball Cap",
                            Sku = "CLTH-010"
                        },
                        new
                        {
                            ProductId = 33,
                            CategoryId = 2,
                            Count = 170,
                            Description = "Premium quality Winter Coat made from comfortable and durable materials",
                            ImageUrl1 = "https://images.unsplash.com/photo-1425100599170-85ec4f00a6ee?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8d2ludGVyJTIwY29hdHxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1519944159858-806d435dc86b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8d2ludGVyJTIwY29hdHxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1548950939-629ecb4d7101?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8d2ludGVyJTIwY29hdHxlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 220000,
                            Name = "Winter Coat",
                            Sku = "CLTH-011"
                        },
                        new
                        {
                            ProductId = 34,
                            CategoryId = 2,
                            Count = 167,
                            Description = "Premium quality Athletic Shoes made from comfortable and durable materials",
                            ImageUrl1 = "https://images.unsplash.com/photo-1765914448113-ebf0ce8cb918?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8QXRobGV0aWMlMjBTaG9lc3xlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1762690285055-fa80848e825b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8QXRobGV0aWMlMjBTaG9lc3xlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl3 = "http://images.unsplash.com/photo-1761942028306-6e0399c10088?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fEF0aGxldGljJTIwU2hvZXN8ZW58MHx8MHx8fDA%3D",
                            ImportPrice = 232000,
                            Name = "Athletic Shoes",
                            Sku = "CLTH-012"
                        },
                        new
                        {
                            ProductId = 35,
                            CategoryId = 2,
                            Count = 164,
                            Description = "Premium quality Casual Sneakers made from comfortable and durable materials",
                            ImageUrl1 = "https://images.unsplash.com/photo-1612942910539-9ff28b2e00d3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Q2FzdWFsJTIwU25lYWtlcnN8ZW58MHx8MHx8fDA%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1759542890353-35f5568c1c90?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Q2FzdWFsJTIwU25lYWtlcnN8ZW58MHx8MHx8fDA%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1736555142217-916540c7f1b7?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8Q2FzdWFsJTIwU25lYWtlcnN8ZW58MHx8MHx8fDA%3D",
                            ImportPrice = 244000,
                            Name = "Casual Sneakers",
                            Sku = "CLTH-013"
                        },
                        new
                        {
                            ProductId = 36,
                            CategoryId = 2,
                            Count = 161,
                            Description = "Premium quality Dress Shoes made from comfortable and durable materials",
                            ImageUrl1 = "https://images.unsplash.com/photo-1552422554-0d5af0c79fc6?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8RHJlc3MlMjBTaG9lc3xlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1472591651607-70e2d88ae3c4?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8RHJlc3MlMjBTaG9lc3xlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1657034321685-1fba1b2751f3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8RHJlc3MlMjBTaG9lc3xlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 256000,
                            Name = "Dress Shoes",
                            Sku = "CLTH-014"
                        },
                        new
                        {
                            ProductId = 37,
                            CategoryId = 2,
                            Count = 158,
                            Description = "Premium quality Sandals made from comfortable and durable materials",
                            ImageUrl1 = "https://images.unsplash.com/photo-1603487742131-4160ec999306?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8U2FuZGFsc3xlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1618615098938-84fc29796e76?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8U2FuZGFsc3xlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1562273138-f46be4ebdf33?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8U2FuZGFsc3xlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 268000,
                            Name = "Sandals",
                            Sku = "CLTH-015"
                        },
                        new
                        {
                            ProductId = 38,
                            CategoryId = 2,
                            Count = 155,
                            Description = "Premium quality Socks Pack made from comfortable and durable materials",
                            ImageUrl1 = "https://images.unsplash.com/photo-1694690127800-68314991ee83?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8U29ja3MlMjBQYWNrfGVufDB8fDB8fHww",
                            ImageUrl2 = "https://images.unsplash.com/photo-1694690890319-4fc2ec85c302?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fFNvY2tzJTIwUGFja3xlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1694690890379-12bb810645ff?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fFNvY2tzJTIwUGFja3xlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 280000,
                            Name = "Socks Pack",
                            Sku = "CLTH-016"
                        },
                        new
                        {
                            ProductId = 39,
                            CategoryId = 2,
                            Count = 152,
                            Description = "Premium quality Leggings made from comfortable and durable materials",
                            ImageUrl1 = "https://images.unsplash.com/photo-1618355281951-a174b87198e2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8TGVnZ2luZ3N8ZW58MHx8MHx8fDA%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1584863495140-a320b13a11a8?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8TGVnZ2luZ3N8ZW58MHx8MHx8fDA%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1618259181324-86a49fe68099?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fExlZ2dpbmdzfGVufDB8fDB8fHww",
                            ImportPrice = 292000,
                            Name = "Leggings",
                            Sku = "CLTH-017"
                        },
                        new
                        {
                            ProductId = 40,
                            CategoryId = 2,
                            Count = 149,
                            Description = "Premium quality Tie made from comfortable and durable materials",
                            ImageUrl1 = "https://images.unsplash.com/photo-1591729652476-e7f587578d9c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8VGllfGVufDB8fDB8fHww",
                            ImageUrl2 = "https://images.unsplash.com/photo-1589756823695-278bc923f962?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8VGllfGVufDB8fDB8fHww",
                            ImageUrl3 = "https://images.unsplash.com/photo-1591729652581-abd20ff6944a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fFRpZXxlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 304000,
                            Name = "Tie",
                            Sku = "CLTH-018"
                        },
                        new
                        {
                            ProductId = 41,
                            CategoryId = 2,
                            Count = 146,
                            Description = "Premium quality Scarf made from comfortable and durable materials",
                            ImageUrl1 = "https://images.unsplash.com/photo-1693382288218-2ce85aa26974?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8c2NhcmZzfGVufDB8fDB8fHww",
                            ImageUrl2 = "https://images.unsplash.com/photo-1669053871927-3df53c13194d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8c2NhcmZzfGVufDB8fDB8fHww",
                            ImageUrl3 = "https://images.unsplash.com/photo-1679934572565-0ceb03f3ec88?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8c2NhcmZzfGVufDB8fDB8fHww",
                            ImportPrice = 316000,
                            Name = "Scarf",
                            Sku = "CLTH-019"
                        },
                        new
                        {
                            ProductId = 42,
                            CategoryId = 2,
                            Count = 143,
                            Description = "Premium quality Gloves made from comfortable and durable materials",
                            ImageUrl1 = "https://images.unsplash.com/photo-1617118602199-d3c05ae37ed8?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8R2xvdmVzfGVufDB8fDB8fHww",
                            ImageUrl2 = "https://images.unsplash.com/photo-1611690889004-c009a7e03712?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8R2xvdmVzfGVufDB8fDB8fHww",
                            ImageUrl3 = "https://images.unsplash.com/photo-1579455134319-042f718340a4?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fEdsb3Zlc3xlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 328000,
                            Name = "Gloves",
                            Sku = "CLTH-020"
                        },
                        new
                        {
                            ProductId = 43,
                            CategoryId = 2,
                            Count = 140,
                            Description = "Premium quality Swim Shorts made from comfortable and durable materials",
                            ImageUrl1 = "https://images.unsplash.com/photo-1631669986792-2bddb5eaf4a0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8U3dpbSUyMFNob3J0c3xlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1631669986788-c094d27280dc?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8U3dpbSUyMFNob3J0c3xlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl3 = "https://plus.unsplash.com/premium_photo-1664392099577-213e2cf77809?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8U3dpbSUyMFNob3J0c3xlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 340000,
                            Name = "Swim Shorts",
                            Sku = "CLTH-021"
                        },
                        new
                        {
                            ProductId = 44,
                            CategoryId = 2,
                            Count = 137,
                            Description = "Premium quality Cargo Pants made from comfortable and durable materials",
                            ImageUrl1 = "https://images.unsplash.com/photo-1584302052177-2e90841dad6a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Q2FyZ28lMjBQYW50c3xlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1548883354-7622d03aca27?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Q2FyZ28lMjBQYW50c3xlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1649850874075-49e014357b9d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Q2FyZ28lMjBQYW50c3xlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 352000,
                            Name = "Cargo Pants",
                            Sku = "CLTH-022"
                        },
                        new
                        {
                            ProductId = 45,
                            CategoryId = 3,
                            Count = 150,
                            Description = "Quality Desk Lamp for your home and garden needs",
                            ImageUrl1 = "https://images.unsplash.com/photo-1621447980929-6638614633c8?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8RGVzayUyMExhbXB8ZW58MHx8MHx8fDA%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1601642964568-1917224f4e4d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8RGVzayUyMExhbXB8ZW58MHx8MHx8fDA%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1526040652367-ac003a0475fe?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8RGVzayUyMExhbXB8ZW58MHx8MHx8fDA%3D",
                            ImportPrice = 75000,
                            Name = "Desk Lamp",
                            Sku = "HOME-001"
                        },
                        new
                        {
                            ProductId = 46,
                            CategoryId = 3,
                            Count = 148,
                            Description = "Quality Wall Clock for your home and garden needs",
                            ImageUrl1 = "https://images.unsplash.com/photo-1564091880021-bb02f2b2928d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8d2FsbCUyMGNsb2NrfGVufDB8fDB8fHww",
                            ImageUrl2 = "https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8d2FsbCUyMGNsb2NrfGVufDB8fDB8fHww",
                            ImageUrl3 = "https://images.unsplash.com/photo-1602162786736-1575a5b1be76?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8d2FsbCUyMGNsb2NrfGVufDB8fDB8fHww",
                            ImportPrice = 95000,
                            Name = "Wall Clock",
                            Sku = "HOME-002"
                        },
                        new
                        {
                            ProductId = 47,
                            CategoryId = 3,
                            Count = 146,
                            Description = "Quality Picture Frame for your home and garden needs",
                            ImageUrl1 = "https://images.unsplash.com/photo-1560828343-a0b3d8864d1b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8UGljdHVyZSUyMEZyYW1lfGVufDB8fDB8fHww",
                            ImageUrl2 = "https://images.unsplash.com/photo-1582053628662-c65b0e0544e9?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8UGljdHVyZSUyMEZyYW1lfGVufDB8fDB8fHww",
                            ImageUrl3 = "https://images.unsplash.com/photo-1611651525144-42027e7f45ba?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8UGljdHVyZSUyMEZyYW1lfGVufDB8fDB8fHww",
                            ImportPrice = 115000,
                            Name = "Picture Frame",
                            Sku = "HOME-003"
                        },
                        new
                        {
                            ProductId = 48,
                            CategoryId = 3,
                            Count = 144,
                            Description = "Quality Yoga Mat for your home and garden needs",
                            ImageUrl1 = "https://images.unsplash.com/photo-1746796751590-a8c0f15d4900?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8ZG9vciUyMG1hdHxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1646239646963-b0b9be56d6b5?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8ZG9vciUyMG1hdHxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1731325632689-7ecab02d39f3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NjJ8fGRvb3IlMjBtYXR8ZW58MHx8MHx8fDA%3D",
                            ImportPrice = 135000,
                            Name = "Yoga Mat",
                            Sku = "HOME-004"
                        },
                        new
                        {
                            ProductId = 49,
                            CategoryId = 3,
                            Count = 142,
                            Description = "Quality Throw Pillow for your home and garden needs",
                            ImageUrl1 = "https://images.unsplash.com/photo-1691256676366-370303d55b61?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8VGhyb3clMjBQaWxsb3d8ZW58MHx8MHx8fDA%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1588706235076-627d896e9f67?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8VGhyb3clMjBQaWxsb3d8ZW58MHx8MHx8fDA%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1615222599276-3d8149bc51ed?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8VGhyb3clMjBQaWxsb3d8ZW58MHx8MHx8fDA%3D",
                            ImportPrice = 155000,
                            Name = "Throw Pillow",
                            Sku = "HOME-005"
                        },
                        new
                        {
                            ProductId = 50,
                            CategoryId = 3,
                            Count = 140,
                            Description = "Quality Bed Sheets for your home and garden needs",
                            ImageUrl1 = "https://images.unsplash.com/photo-1542728929-2b5d9a0c8d48?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8QmVkJTIwU2hlZXRzfGVufDB8fDB8fHww",
                            ImageUrl2 = "https://images.unsplash.com/photo-1601276174812-63280a55656e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8QmVkJTIwU2hlZXRzfGVufDB8fDB8fHww",
                            ImageUrl3 = "https://images.unsplash.com/photo-1617744257724-6fafec25442f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8QmVkJTIwU2hlZXRzfGVufDB8fDB8fHww",
                            ImportPrice = 175000,
                            Name = "Bed Sheets",
                            Sku = "HOME-006"
                        },
                        new
                        {
                            ProductId = 51,
                            CategoryId = 3,
                            Count = 138,
                            Description = "Quality Towel Set for your home and garden needs",
                            ImageUrl1 = "https://images.unsplash.com/photo-1766727923624-2e8eede5aa8c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8VG93ZWwlMjBTZXR8ZW58MHx8MHx8fDA%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1739922039544-76de5a8f3077?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fFRvd2VsJTIwU2V0fGVufDB8fDB8fHww",
                            ImageUrl3 = "https://images.unsplash.com/photo-1737065183310-aef762bd011c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fFRvd2VsJTIwU2V0fGVufDB8fDB8fHww",
                            ImportPrice = 195000,
                            Name = "Towel Set",
                            Sku = "HOME-007"
                        },
                        new
                        {
                            ProductId = 52,
                            CategoryId = 3,
                            Count = 136,
                            Description = "Quality Kitchen Knife Set for your home and garden needs",
                            ImageUrl1 = "https://images.unsplash.com/photo-1764177406219-2b4bf3dab69c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8S2l0Y2hlbiUyMEtuaWZlJTIwU2V0fGVufDB8fDB8fHww",
                            ImageUrl2 = "https://images.unsplash.com/photo-1674660346036-4b3df3f07cca?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fEtpdGNoZW4lMjBLbmlmZSUyMFNldHxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1609467334293-030ac6448fd8?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fEtpdGNoZW4lMjBLbmlmZSUyMFNldHxlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 215000,
                            Name = "Kitchen Knife Set",
                            Sku = "HOME-008"
                        },
                        new
                        {
                            ProductId = 53,
                            CategoryId = 3,
                            Count = 134,
                            Description = "Quality Coffee Maker for your home and garden needs",
                            ImageUrl1 = "https://images.unsplash.com/photo-1608354580875-30bd4168b351?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y29mZmVlJTIwTWFrZXJ8ZW58MHx8MHx8fDA%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1707241358597-bafcc8a8e73d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Y29mZmVlJTIwTWFrZXJ8ZW58MHx8MHx8fDA%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1545936055-22b27770efca?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGNvZmZlZSUyME1ha2VyfGVufDB8fDB8fHww",
                            ImportPrice = 235000,
                            Name = "Coffee Maker",
                            Sku = "HOME-009"
                        },
                        new
                        {
                            ProductId = 54,
                            CategoryId = 3,
                            Count = 132,
                            Description = "Quality Blender for your home and garden needs",
                            ImageUrl1 = "https://images.unsplash.com/photo-1585237672814-8f85a8118bf6?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmxlbmRlcnN8ZW58MHx8MHx8fDA%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bWl4ZXVyfGVufDB8fDB8fHww",
                            ImageUrl3 = "https://images.unsplash.com/photo-1622818426197-d54f85b88690?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8bWl4ZXVyfGVufDB8fDB8fHww",
                            ImportPrice = 255000,
                            Name = "Blender",
                            Sku = "HOME-010"
                        },
                        new
                        {
                            ProductId = 55,
                            CategoryId = 3,
                            Count = 130,
                            Description = "Quality Cutting Board for your home and garden needs",
                            ImageUrl1 = "https://images.unsplash.com/photo-1666013942797-9daa4b8b3b4f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Q3V0dGluZyUyMEJvYXJkfGVufDB8fDB8fHww",
                            ImageUrl2 = "https://images.unsplash.com/photo-1587302108992-20648821725d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8Q3V0dGluZyUyMEJvYXJkfGVufDB8fDB8fHww",
                            ImageUrl3 = "https://images.unsplash.com/photo-1624811533744-f85d5325d49c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Q3V0dGluZyUyMEJvYXJkfGVufDB8fDB8fHww",
                            ImportPrice = 275000,
                            Name = "Cutting Board",
                            Sku = "HOME-011"
                        },
                        new
                        {
                            ProductId = 56,
                            CategoryId = 3,
                            Count = 128,
                            Description = "Quality Storage Boxes for your home and garden needs",
                            ImageUrl1 = "https://images.unsplash.com/photo-1609143739217-01b60dad1c67?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8U3RvcmFnZSUyMEJveGVzfGVufDB8fDB8fHww",
                            ImageUrl2 = "https://images.unsplash.com/photo-1766040923580-16ad32fae8b4?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8U3RvcmFnZSUyMEJveGVzfGVufDB8fDB8fHww",
                            ImageUrl3 = "https://images.unsplash.com/photo-1659729751444-dd8e40685a4f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fFN0b3JhZ2UlMjBCb3hlc3xlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 295000,
                            Name = "Storage Boxes",
                            Sku = "HOME-012"
                        },
                        new
                        {
                            ProductId = 57,
                            CategoryId = 3,
                            Count = 126,
                            Description = "Quality Plant Pot for your home and garden needs",
                            ImageUrl1 = "https://images.unsplash.com/photo-1609061801093-1b7a8a574c69?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8UGxhbnQlMjBQb3R8ZW58MHx8MHx8fDA%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1588440691140-09155c1be58a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8UGxhbnQlMjBQb3R8ZW58MHx8MHx8fDA%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1563419837758-e48ef1b731dd?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8UGxhbnQlMjBQb3R8ZW58MHx8MHx8fDA%3D",
                            ImportPrice = 315000,
                            Name = "Plant Pot",
                            Sku = "HOME-013"
                        },
                        new
                        {
                            ProductId = 58,
                            CategoryId = 3,
                            Count = 124,
                            Description = "Quality Garden Shovel for your home and garden needs",
                            ImageUrl1 = "https://images.unsplash.com/photo-1562090098-1929cdffc7c2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8R2FyZGVuJTIwU2hvdmVsfGVufDB8fDB8fHww",
                            ImageUrl2 = "https://images.unsplash.com/photo-1597868233489-5be16be259ed?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8R2FyZGVuJTIwU2hvdmVsfGVufDB8fDB8fHww",
                            ImageUrl3 = "https://images.unsplash.com/photo-1712912828055-3d01804a1c73?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8R2FyZGVuJTIwU2hvdmVsfGVufDB8fDB8fHww",
                            ImportPrice = 335000,
                            Name = "Garden Shovel",
                            Sku = "HOME-014"
                        },
                        new
                        {
                            ProductId = 59,
                            CategoryId = 3,
                            Count = 122,
                            Description = "Quality Watering Can for your home and garden needs",
                            ImageUrl1 = "https://images.unsplash.com/photo-1599277100479-3252d492a19a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8V2F0ZXJpbmclMjBDYW58ZW58MHx8MHx8fDA%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1515150144380-bca9f1650ed9?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8V2F0ZXJpbmclMjBDYW58ZW58MHx8MHx8fDA%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1661880667340-625347ecf85b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8V2F0ZXJpbmclMjBDYW58ZW58MHx8MHx8fDA%3D",
                            ImportPrice = 355000,
                            Name = "Watering Can",
                            Sku = "HOME-015"
                        },
                        new
                        {
                            ProductId = 60,
                            CategoryId = 3,
                            Count = 120,
                            Description = "Quality Pruning Shears for your home and garden needs",
                            ImageUrl1 = "https://images.unsplash.com/photo-1588311082740-88c1b480d72d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8UHJ1bmluZyUyMFNoZWFyc3xlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1680124744737-03fb697f303d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8UHJ1bmluZyUyMFNoZWFyc3xlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1680124744736-859f16257ef0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8UHJ1bmluZyUyMFNoZWFyc3xlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 375000,
                            Name = "Pruning Shears",
                            Sku = "HOME-016"
                        },
                        new
                        {
                            ProductId = 61,
                            CategoryId = 3,
                            Count = 118,
                            Description = "Quality Bird Feeder for your home and garden needs",
                            ImageUrl1 = "https://images.unsplash.com/photo-1598280860721-14d1fd80a8af?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8QmlyZCUyMEZlZWRlcnxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1590238750866-f99d3febe496?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8QmlyZCUyMEZlZWRlcnxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1621807147195-580cddd8f758?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8QmlyZCUyMEZlZWRlcnxlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 395000,
                            Name = "Bird Feeder",
                            Sku = "HOME-017"
                        },
                        new
                        {
                            ProductId = 62,
                            CategoryId = 3,
                            Count = 116,
                            Description = "Quality Garden Hose for your home and garden needs",
                            ImageUrl1 = "https://images.unsplash.com/photo-1693776472225-be367ccf88b7?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Z2FyZGVuJTIwaG9zZXxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1586876757274-7ba27e45cd6b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Z2FyZGVuJTIwaG9zZXxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1684867430779-e66e779a19b7?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8Z2FyZGVuJTIwaG9zZXxlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 415000,
                            Name = "Garden Hose",
                            Sku = "HOME-018"
                        },
                        new
                        {
                            ProductId = 63,
                            CategoryId = 3,
                            Count = 114,
                            Description = "Quality Outdoor Chair for your home and garden needs",
                            ImageUrl1 = "https://images.unsplash.com/photo-1622789095519-c6a1accef0a6?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8b3V0ZG9vciUyMGNoYWlyc3xlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1767014732583-7cf8e781f72e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8b3V0ZG9vciUyMGNoYWlyc3xlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1764090550152-23b8dbf2908f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8b3V0ZG9vciUyMGNoYWlyc3xlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 435000,
                            Name = "Outdoor Chair",
                            Sku = "HOME-019"
                        },
                        new
                        {
                            ProductId = 64,
                            CategoryId = 3,
                            Count = 112,
                            Description = "Quality Table Lamp for your home and garden needs",
                            ImageUrl1 = "https://images.unsplash.com/photo-1642689703534-e41f29622078?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8VGFibGUlMjBMYW1wfGVufDB8fDB8fHww",
                            ImageUrl2 = "https://images.unsplash.com/photo-1580130281320-0ef0754f2bf7?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8VGFibGUlMjBMYW1wfGVufDB8fDB8fHww",
                            ImageUrl3 = "https://images.unsplash.com/photo-1573676386604-78f8ed228e2b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8VGFibGUlMjBMYW1wfGVufDB8fDB8fHww",
                            ImportPrice = 455000,
                            Name = "Table Lamp",
                            Sku = "HOME-020"
                        },
                        new
                        {
                            ProductId = 65,
                            CategoryId = 3,
                            Count = 110,
                            Description = "Quality Mirror for your home and garden needs",
                            ImageUrl1 = "https://images.unsplash.com/photo-1519577918463-484ce33e1ecb?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8TWlycm9yfGVufDB8fDB8fHww",
                            ImageUrl2 = "https://images.unsplash.com/photo-1656797590428-653803a957fd?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8TWlycm9yfGVufDB8fDB8fHww",
                            ImageUrl3 = "https://images.unsplash.com/photo-1620416264626-84e3c7dbe91f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fE1pcnJvcnxlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 475000,
                            Name = "Mirror",
                            Sku = "HOME-021"
                        },
                        new
                        {
                            ProductId = 66,
                            CategoryId = 3,
                            Count = 108,
                            Description = "Quality Curtain for your home and garden needs",
                            ImageUrl1 = "https://images.unsplash.com/photo-1734498230542-b36f63c17f85?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Q3VydGFpbiUyMFJvZHxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl2 = "https://images.unsplash.com/photo-1593909840438-48825492a8b7?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Q3VydGFpbiUyMFJvZHxlbnwwfHwwfHx8MA%3D%3D",
                            ImageUrl3 = "https://images.unsplash.com/photo-1539208175673-6b9149754096?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8Q3VydGFpbiUyMFJvZHxlbnwwfHwwfHx8MA%3D%3D",
                            ImportPrice = 495000,
                            Name = "Curtain",
                            Sku = "HOME-022"
                        });
                });

            modelBuilder.Entity("MyShop.Data.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyShop.Data.Models.OrderItem", b =>
                {
                    b.HasOne("MyShop.Data.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyShop.Data.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MyShop.Data.Models.Product", b =>
                {
                    b.HasOne("MyShop.Data.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyShop.Data.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MyShop.Data.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("MyShop.Data.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
